### ISSUE TITLE
Provide a content model to get started quickly

### ISSUE THREAD

**Issue by stefanjudis** [faesel/gatsby-techblog-starter#1]
Heyooo, thank you for putting this starter together. I wonder If you'd be up for including an example content model inside of this project (similar to how it is done [in other examples](https://github.com/vercel/next.js/tree/master/examples/cms-contentful#run-a-script-to-create-the-content-model)).

Having a content model available would allow people to install and set up Contentful with a single command. 

What do you think? :)

**Comment by faesel** [comment]
That's really cool, I didn't know you could do that! I will add it to the list.

**Comment by stefanjudis** [comment]
Nice!!! If you did, let me know, i'd love to give it a spin and maybe share it with the Contentful community (I work for Contentful 🙈). :)

**Comment by faesel** [comment]
I've added that in, thanks for the suggestion.
